---
- hosts: all
  become: true

  tasks:
    - name: Install Apache and PHP modules
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_os_family in ["Debian", "Ubuntu"]

    - name: Install apache and PHP for CentOS and RedHat
      dnf:
        name:
          - httpd
          - php
        state: latest
        update_cache: yes
      when: ansible_os_family in ["RedHat", "CentOS"]
